# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/boysanic/commission_hw/commission_coproc/commission_coproc.srcs/sources_1/ip/add_u32/add_u32.xci
# IP: The module: 'add_u32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/boysanic/commission_hw/commission_coproc/commission_coproc.gen/sources_1/ip/add_u32/add_u32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_u32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/boysanic/commission_hw/commission_coproc/commission_coproc.srcs/sources_1/ip/add_u32/add_u32.xci
# IP: The module: 'add_u32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/boysanic/commission_hw/commission_coproc/commission_coproc.gen/sources_1/ip/add_u32/add_u32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_u32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
