# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/boysanic/commission_hw/commission_coproc/commission_coproc.srcs/sources_1/ip/pcie_controller/pcie_controller.xci
# IP: The module: 'pcie_controller' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/boysanic/commission_hw/commission_coproc/commission_coproc.gen/sources_1/ip/pcie_controller/source/pcie_controller-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_controller'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/boysanic/commission_hw/commission_coproc/commission_coproc.gen/sources_1/ip/pcie_controller/source/ip_xilinx_pcie_2_1_7x_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/boysanic/commission_hw/commission_coproc/commission_coproc.gen/sources_1/ip/pcie_controller/synth/pcie_controller_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/boysanic/commission_hw/commission_coproc/commission_coproc.srcs/sources_1/ip/pcie_controller/pcie_controller.xci
# IP: The module: 'pcie_controller' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/boysanic/commission_hw/commission_coproc/commission_coproc.gen/sources_1/ip/pcie_controller/source/pcie_controller-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/boysanic/commission_hw/commission_coproc/commission_coproc.gen/sources_1/ip/pcie_controller/source/ip_xilinx_pcie_2_1_7x_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/boysanic/commission_hw/commission_coproc/commission_coproc.gen/sources_1/ip/pcie_controller/synth/pcie_controller_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
